server:
  port: 8080

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:p6spy:mysql://127.0.0.1:3306/quick-boot
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
